#!/usr/bin/with-contenv sh
# shellcheck shell=bash
# From https://github.com/smebberson/docker-alpine/tree/master/alpine-apache

exec /usr/bin/svnserve -d --foreground -r /data/svn --listen-port 3690;